{
 "title": "Ecommerce - Overview",
 "tags": [
  "ecommerce",
  "microservices"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "API Gateway Requests per Second",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(api_gateway_requests_total[5m])",
     "legendFormat": "gateway"
    }
   ]
  },
  {
   "title": "Average API Gateway Response Time (s)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "api_gateway_response_time_seconds",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Orders Created per Minute",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(order_total_created_total[5m])",
     "legendFormat": "orders created"
    }
   ]
  },
  {
   "title": "Order Value per Minute",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(order_total_value_total[5m])",
     "legendFormat": "€ / min"
    }
   ]
  },
  {
   "title": "Orders by Status",
   "type": "bargauge",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    { "expr": "order_status_count", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Order Service Request Duration (p95)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(order_service_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  }
 ]
}